---
# Windows Hosts Variables
# These variables are used for all Windows hosts (workstations)

# WinRM Configuration
ansible_connection: winrm
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore
ansible_port: 5985

# Disable become (sudo) - not applicable for Windows
ansible_become: false
ansible_become_method: runas
