---

- name: Join domain
  microsoft.ad.membership:
    dns_domain_name: "{{ domain_name }}"
    domain_admin_user: "{{ win_username }}@{{ domain_name }}"
    domain_admin_password: "{{ win_password }}"
    state: domain
  register: domain_join

- name: Reboot if domain join changed
  ansible.windows.win_reboot:
  when: domain_join.reboot_required
