---
# Linux Hosts Variables
# These variables are used for all Linux hosts (including infra via inheritance)

# SSH Connection
ansible_connection: ssh
ansible_user: sysadmin
ansible_ssh_private_key_file: /home/jackfrost/.ssh/id_rsa

# Privilege Escalation
ansible_become: true
ansible_become_method: sudo
