---
suricata_interface: "{{ ansible_default_ipv4.interface | default('eth0') }}"
suricata_home_net: "[172.16.10.0/24]"
suricata_external_net: "any"
suricata_rules_url: "https://rules.emergingthreats.net/open/suricata-6.0.8/emerging.rules.tar.gz"
