- include_vars: "{{ playbook_dir }}/../inventory/group_vars/secret_vault.yml"
  tags: always

- import_tasks: prerequisites.yml
  tags: prerequisites

- import_tasks: cassandra.yml
  tags: cassandra

- import_tasks: cassandra_init.yml
  tags: cassandra_init

- import_tasks: elastic_init.yml
  tags: elastic_init

- import_tasks: install_thehive.yml
  tags: install_thehive

- import_tasks: secure_thehive.yml
  tags: secure_thehive

- import_tasks: configure_organization.yml
  tags: configure_organization

