---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  become: yes

- name: Configure Nginx Default Site
  template:
    src: nginx_default.j2
    dest: /etc/nginx/sites-enabled/default
  become: yes
  notify: Restart Nginx

- name: Start and Enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: yes
