---
- name: Add Suricata PPA
  ansible.builtin.apt_repository:
    repo: ppa:oisf/suricata-stable
    state: present
    update_cache: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Suricata and dependencies
  ansible.builtin.apt:
    name:
      - suricata
      - net-tools
    state: present
